[phases.setup]
nixPkgs = ["python311", "gcc", "libffi", "openssl", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip poetry",
  "cd source/web_service && poetry config virtualenvs.create false && poetry install --no-root --no-interaction --no-ansi"
]

[start]
cmd = "bash railway-start.sh"
